// Generated by GitHub Copilot
import * as ImagePicker from "expo-image-picker";
import React from "react";
import {
  ActivityIndicator,
  Alert,
  Image,
  Pressable,
  SafeAreaView,
  ScrollView,
  StyleSheet,
  Text,
  TextInput,
  View
} from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";

import { generateVideo, uploadImage } from "../services/api";
import { useVideoStore } from "../store/videoStore";
import type { RootStackParamList } from "../App";

type Props = NativeStackScreenProps<RootStackParamList, "CreateVideo">;

/**
 * Screen for image selection and generation input configuration.
 */
export default function CreateVideoScreen({ navigation }: Props): React.JSX.Element {
  const {
    input,
    setImageUri,
    setImageId,
    setPrompt,
    setDuration,
    setAspectRatio,
    setCurrentJob,
    setError,
    isLoading,
    setIsLoading
  } = useVideoStore();

  const onPickImage = async (): Promise<void> => {
    const permission = await ImagePicker.requestMediaLibraryPermissionsAsync();
    if (!permission.granted) {
      Alert.alert("Permission needed", "Enable photo permissions to pick an image.");
      return;
    }

    const result = await ImagePicker.launchImageLibraryAsync({
      mediaTypes: ImagePicker.MediaTypeOptions.Images,
      allowsEditing: true,
      quality: 0.9
    });

    if (!result.canceled && result.assets[0]) {
      setImageUri(result.assets[0].uri);
    }
  };

  const onCreateVideo = async (): Promise<void> => {
    if (!input.imageUri) {
      Alert.alert("Missing image", "Please select an image first.");
      return;
    }
    if (!input.prompt.trim()) {
      Alert.alert("Missing prompt", "Please describe the motion you want.");
      return;
    }

    setIsLoading(true);
    setError(null);

    try {
      const upload = await uploadImage(input.imageUri);
      setImageId(upload.image_id);

      const response = await generateVideo({
        image_id: upload.image_id,
        prompt: input.prompt,
        duration_seconds: input.durationSeconds,
        aspect_ratio: input.aspectRatio
      });

      setCurrentJob(response.job);
      navigation.navigate("Progress");
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to generate video";
      setError(message);
      Alert.alert("Generation failed", message);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <SafeAreaView style={styles.container}>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.title}>Create Motion Video</Text>
        <Text style={styles.subtitle}>Upload one image and describe the movement you want.</Text>

        <Pressable style={styles.imagePicker} onPress={onPickImage} accessibilityLabel="Pick image">
          {input.imageUri ? (
            <Image source={{ uri: input.imageUri }} style={styles.previewImage} />
          ) : (
            <Text style={styles.imagePickerText}>Tap to select image</Text>
          )}
        </Pressable>

        <TextInput
          style={styles.promptInput}
          placeholder="Example: Gentle camera push-in with hair and dress flowing in the wind"
          value={input.prompt}
          onChangeText={setPrompt}
          multiline
        />

        <Text style={styles.label}>Duration</Text>
        <View style={styles.row}>
          {[3, 4, 6, 8].map((duration) => (
            <Pressable
              key={duration}
              style={[styles.option, input.durationSeconds === duration && styles.optionSelected]}
              onPress={() => setDuration(duration)}
            >
              <Text style={[styles.optionText, input.durationSeconds === duration && styles.optionTextSelected]}>{duration}s</Text>
            </Pressable>
          ))}
        </View>

        <Text style={styles.label}>Aspect Ratio</Text>
        <View style={styles.row}>
          {(["9:16", "1:1", "16:9"] as const).map((ratio) => (
            <Pressable
              key={ratio}
              style={[styles.option, input.aspectRatio === ratio && styles.optionSelected]}
              onPress={() => setAspectRatio(ratio)}
            >
              <Text style={[styles.optionText, input.aspectRatio === ratio && styles.optionTextSelected]}>{ratio}</Text>
            </Pressable>
          ))}
        </View>

        <Pressable style={styles.generateButton} onPress={onCreateVideo} disabled={isLoading}>
          {isLoading ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.generateButtonText}>Generate Video</Text>}
        </Pressable>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2"
  },
  content: {
    padding: 20,
    gap: 14
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1C1A16"
  },
  subtitle: {
    color: "#5B554B",
    fontSize: 15
  },
  imagePicker: {
    marginTop: 8,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#D5CCBE",
    minHeight: 220,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    backgroundColor: "#EFE8DB"
  },
  imagePickerText: {
    color: "#6B6458",
    fontSize: 16,
    fontWeight: "600"
  },
  previewImage: {
    width: "100%",
    height: 280
  },
  promptInput: {
    minHeight: 110,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D5CCBE",
    backgroundColor: "#FFFFFF",
    padding: 12,
    textAlignVertical: "top"
  },
  label: {
    fontWeight: "700",
    color: "#2A251D"
  },
  row: {
    flexDirection: "row",
    gap: 10
  },
  option: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C9BDAA",
    backgroundColor: "#FFFFFF"
  },
  optionSelected: {
    backgroundColor: "#2A7A67",
    borderColor: "#2A7A67"
  },
  optionText: {
    color: "#3E382F",
    fontWeight: "600"
  },
  optionTextSelected: {
    color: "#FFFFFF"
  },
  generateButton: {
    marginTop: 10,
    backgroundColor: "#1D5F52",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center"
  },
  generateButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "700"
  }
});
