// Generated by GitHub Copilot
import React from "react";
import { Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";

import type { RootStackParamList } from "../App";

type Props = NativeStackScreenProps<RootStackParamList, "Home">;

/**
 * Entry screen with quick navigation to key product actions.
 */
export default function HomeScreen({ navigation }: Props): React.JSX.Element {
  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.hero}>
        <Text style={styles.title}>Photo Motion AI</Text>
        <Text style={styles.subtitle}>Turn one photo into a cinematic short video in seconds.</Text>
      </View>

      <Pressable style={styles.primaryButton} onPress={() => navigation.navigate("CreateVideo")}>
        <Text style={styles.primaryButtonText}>Create New Video</Text>
      </Pressable>

      <View style={styles.row}>
        <Pressable style={styles.secondaryButton} onPress={() => navigation.navigate("MyVideos")}>
          <Text style={styles.secondaryText}>My Videos</Text>
        </Pressable>
        <Pressable style={styles.secondaryButton} onPress={() => navigation.navigate("Settings")}>
          <Text style={styles.secondaryText}>Settings</Text>
        </Pressable>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2",
    padding: 22,
    justifyContent: "center",
    gap: 20
  },
  hero: {
    gap: 8
  },
  title: {
    fontSize: 36,
    fontWeight: "800",
    color: "#1A1712"
  },
  subtitle: {
    color: "#5F574B",
    fontSize: 16,
    lineHeight: 22
  },
  primaryButton: {
    backgroundColor: "#1D5F52",
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: "center"
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 17
  },
  row: {
    flexDirection: "row",
    gap: 12
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#CFBFA9",
    alignItems: "center",
    paddingVertical: 13,
    backgroundColor: "#FFFFFF"
  },
  secondaryText: {
    color: "#383227",
    fontWeight: "600"
  }
});
