// Generated by GitHub Copilot
import React, { useEffect, useState } from "react";
import { FlatList, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";

import { listVideos } from "../services/api";
import { useVideoStore } from "../store/videoStore";
import type { RootStackParamList } from "../App";

type Props = NativeStackScreenProps<RootStackParamList, "MyVideos">;

/**
 * Screen showing generated videos from backend and local cache.
 */
export default function MyVideosScreen({ navigation }: Props): React.JSX.Element {
  const { myVideos, setMyVideos, setCurrentVideo } = useVideoStore();
  const [isRefreshing, setIsRefreshing] = useState(false);

  const refresh = async (): Promise<void> => {
    setIsRefreshing(true);
    try {
      const remoteVideos = await listVideos();
      setMyVideos(remoteVideos);
    } finally {
      setIsRefreshing(false);
    }
  };

  useEffect(() => {
    void refresh();
  }, []);

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.headerRow}>
        <Text style={styles.title}>My Videos</Text>
        <Pressable style={styles.refreshButton} onPress={refresh}>
          <Text style={styles.refreshButtonText}>{isRefreshing ? "Refreshing..." : "Refresh"}</Text>
        </Pressable>
      </View>

      <FlatList
        data={myVideos}
        keyExtractor={(item) => item.id}
        contentContainerStyle={styles.list}
        ListEmptyComponent={<Text style={styles.empty}>No videos yet. Create your first one.</Text>}
        renderItem={({ item }) => (
          <Pressable
            style={styles.card}
            onPress={() => {
              setCurrentVideo(item);
              navigation.navigate("Preview");
            }}
          >
            <Text style={styles.cardTitle}>{item.prompt}</Text>
            <Text style={styles.cardMeta}>{item.duration_seconds}s • {item.aspect_ratio}</Text>
            <Text style={styles.cardMeta}>{new Date(item.created_at).toLocaleString()}</Text>
          </Pressable>
        )}
      />
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2",
    padding: 20
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1D1A15"
  },
  refreshButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#CBBEA9",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "#FFFFFF"
  },
  refreshButtonText: {
    color: "#3E372D",
    fontWeight: "600"
  },
  list: {
    gap: 10,
    paddingBottom: 20
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E0D5C6",
    borderRadius: 14,
    padding: 14,
    gap: 6
  },
  cardTitle: {
    fontWeight: "700",
    color: "#2C271F"
  },
  cardMeta: {
    color: "#625B4F",
    fontSize: 13
  },
  empty: {
    textAlign: "center",
    color: "#625B4F",
    marginTop: 40
  }
});
