// Generated by GitHub Copilot
import { Video, ResizeMode } from "expo-av";
import React from "react";
import { Alert, Pressable, SafeAreaView, Share, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";

import { useVideoStore } from "../store/videoStore";
import type { RootStackParamList } from "../App";

type Props = NativeStackScreenProps<RootStackParamList, "Preview">;

/**
 * Screen displaying the generated video and quick follow-up actions.
 */
export default function PreviewScreen({ navigation }: Props): React.JSX.Element {
  const { currentVideo, myVideos, setMyVideos } = useVideoStore();

  const onShare = async (): Promise<void> => {
    if (!currentVideo?.video_url) {
      return;
    }
    await Share.share({ message: `Check my generated video: ${currentVideo.video_url}` });
  };

  const onSave = (): void => {
    if (!currentVideo) {
      return;
    }

    const exists = myVideos.some((item) => item.id === currentVideo.id);
    if (!exists) {
      setMyVideos([currentVideo, ...myVideos]);
    }

    Alert.alert("Saved", "Video saved to My Videos.");
  };

  if (!currentVideo) {
    return (
      <SafeAreaView style={styles.container}>
        <Text style={styles.emptyText}>No video available yet.</Text>
      </SafeAreaView>
    );
  }

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.videoCard}>
        <Video
          source={{ uri: currentVideo.video_url }}
          style={styles.video}
          useNativeControls
          resizeMode={ResizeMode.CONTAIN}
          isLooping
          shouldPlay
        />
      </View>

      <Text style={styles.meta}>Prompt: {currentVideo.prompt}</Text>
      <Text style={styles.meta}>Duration: {currentVideo.duration_seconds}s</Text>
      <Text style={styles.meta}>Aspect ratio: {currentVideo.aspect_ratio}</Text>

      <View style={styles.row}>
        <Pressable style={styles.secondaryButton} onPress={onSave}>
          <Text style={styles.secondaryButtonText}>Save</Text>
        </Pressable>
        <Pressable style={styles.secondaryButton} onPress={onShare}>
          <Text style={styles.secondaryButtonText}>Share</Text>
        </Pressable>
      </View>

      <Pressable style={styles.primaryButton} onPress={() => navigation.navigate("CreateVideo")}>
        <Text style={styles.primaryButtonText}>Regenerate</Text>
      </Pressable>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2",
    padding: 20,
    gap: 12
  },
  videoCard: {
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#D9CFBE",
    backgroundColor: "#171512",
    height: 380
  },
  video: {
    width: "100%",
    height: "100%"
  },
  meta: {
    color: "#3A342A"
  },
  row: {
    flexDirection: "row",
    gap: 12,
    marginTop: 8
  },
  secondaryButton: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#C6B89F",
    alignItems: "center",
    paddingVertical: 12,
    backgroundColor: "#FFFFFF"
  },
  secondaryButtonText: {
    color: "#3A342A",
    fontWeight: "600"
  },
  primaryButton: {
    borderRadius: 12,
    alignItems: "center",
    paddingVertical: 14,
    backgroundColor: "#1D5F52"
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontWeight: "700"
  },
  emptyText: {
    marginTop: 40,
    textAlign: "center",
    color: "#5B554B"
  }
});
