// Generated by GitHub Copilot
import React, { useEffect } from "react";
import { ActivityIndicator, SafeAreaView, StyleSheet, Text, View } from "react-native";
import type { NativeStackScreenProps } from "@react-navigation/native-stack";

import { getVideo, getJob } from "../services/api";
import { useVideoStore } from "../store/videoStore";
import type { RootStackParamList } from "../App";

type Props = NativeStackScreenProps<RootStackParamList, "Progress">;

/**
 * Screen that polls backend job state until completion or failure.
 */
export default function ProgressScreen({ navigation }: Props): React.JSX.Element {
  const { currentJob, setCurrentJob, setCurrentVideo, setError } = useVideoStore();

  useEffect(() => {
    if (!currentJob?.id) {
      navigation.replace("CreateVideo");
      return;
    }

    let isActive = true;

    const timer = setInterval(async () => {
      try {
        const latest = await getJob(currentJob.id);
        if (!isActive) {
          return;
        }

        setCurrentJob(latest);

        if (latest.status === "completed" && latest.video_id) {
          const video = await getVideo(latest.video_id);
          if (!isActive) {
            return;
          }
          setCurrentVideo(video);
          clearInterval(timer);
          navigation.replace("Preview");
        }

        if (latest.status === "failed") {
          clearInterval(timer);
          setError(latest.error ?? "Video generation failed.");
          navigation.replace("CreateVideo");
        }
      } catch (error) {
        clearInterval(timer);
        const message = error instanceof Error ? error.message : "Polling failed";
        setError(message);
        navigation.replace("CreateVideo");
      }
    }, 1500);

    return () => {
      isActive = false;
      clearInterval(timer);
    };
  }, [currentJob?.id, navigation, setCurrentJob, setCurrentVideo, setError]);

  return (
    <SafeAreaView style={styles.container}>
      <View style={styles.card}>
        <ActivityIndicator size="large" color="#1D5F52" />
        <Text style={styles.title}>Creating your video...</Text>
        <Text style={styles.subtitle}>This usually takes a few seconds with the mock provider.</Text>
        <Text style={styles.status}>Status: {currentJob?.status ?? "queued"}</Text>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2",
    justifyContent: "center",
    padding: 20
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#E2D8C8",
    padding: 22,
    alignItems: "center",
    gap: 12
  },
  title: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1C1A16"
  },
  subtitle: {
    textAlign: "center",
    color: "#645E52"
  },
  status: {
    marginTop: 4,
    fontWeight: "600",
    color: "#2A251D"
  }
});
