// Generated by GitHub Copilot
import React from "react";
import { Alert, Pressable, SafeAreaView, StyleSheet, Text, View } from "react-native";

/**
 * Settings placeholder for future auth/credits/subscription features.
 */
export default function SettingsScreen(): React.JSX.Element {
  return (
    <SafeAreaView style={styles.container}>
      <Text style={styles.title}>Settings</Text>
      <View style={styles.card}>
        <Text style={styles.itemTitle}>Provider Mode</Text>
        <Text style={styles.itemSub}>Mock provider (local dev)</Text>
      </View>

      <Pressable
        style={styles.button}
        onPress={() =>
          Alert.alert(
            "Coming soon",
            "Auth, credits, and subscription management can be added here."
          )
        }
      >
        <Text style={styles.buttonText}>Manage Account</Text>
      </Pressable>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAF8F2",
    padding: 20,
    gap: 14
  },
  title: {
    fontSize: 28,
    fontWeight: "700",
    color: "#1E1A15"
  },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#D9CFBF",
    backgroundColor: "#FFFFFF",
    padding: 14,
    gap: 4
  },
  itemTitle: {
    fontWeight: "700",
    color: "#2F2A20"
  },
  itemSub: {
    color: "#675F53"
  },
  button: {
    borderRadius: 12,
    backgroundColor: "#1D5F52",
    paddingVertical: 14,
    alignItems: "center"
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "700"
  }
});
