// Generated by GitHub Copilot
import { create } from "zustand";

import type { AspectRatio, JobResponse, VideoResponse } from "../services/api";

interface GenerationInput {
  imageUri: string | null;
  imageId: string | null;
  prompt: string;
  durationSeconds: number;
  aspectRatio: AspectRatio;
}

interface VideoStoreState {
  input: GenerationInput;
  currentJob: JobResponse | null;
  currentVideo: VideoResponse | null;
  myVideos: VideoResponse[];
  isLoading: boolean;
  error: string | null;
  setImageUri: (uri: string | null) => void;
  setImageId: (imageId: string | null) => void;
  setPrompt: (prompt: string) => void;
  setDuration: (durationSeconds: number) => void;
  setAspectRatio: (aspectRatio: AspectRatio) => void;
  setCurrentJob: (job: JobResponse | null) => void;
  setCurrentVideo: (video: VideoResponse | null) => void;
  setMyVideos: (videos: VideoResponse[]) => void;
  setIsLoading: (isLoading: boolean) => void;
  setError: (error: string | null) => void;
  resetGeneration: () => void;
}

const initialInput: GenerationInput = {
  imageUri: null,
  imageId: null,
  prompt: "",
  durationSeconds: 4,
  aspectRatio: "9:16"
};

export const useVideoStore = create<VideoStoreState>((set) => ({
  input: initialInput,
  currentJob: null,
  currentVideo: null,
  myVideos: [],
  isLoading: false,
  error: null,
  setImageUri: (imageUri: string | null) =>
    set((state: VideoStoreState) => ({ input: { ...state.input, imageUri } })),
  setImageId: (imageId: string | null) =>
    set((state: VideoStoreState) => ({ input: { ...state.input, imageId } })),
  setPrompt: (prompt: string) =>
    set((state: VideoStoreState) => ({ input: { ...state.input, prompt } })),
  setDuration: (durationSeconds: number) =>
    set((state: VideoStoreState) => ({ input: { ...state.input, durationSeconds } })),
  setAspectRatio: (aspectRatio: AspectRatio) =>
    set((state: VideoStoreState) => ({ input: { ...state.input, aspectRatio } })),
  setCurrentJob: (currentJob: JobResponse | null) => set({ currentJob }),
  setCurrentVideo: (currentVideo: VideoResponse | null) => set({ currentVideo }),
  setMyVideos: (myVideos: VideoResponse[]) => set({ myVideos }),
  setIsLoading: (isLoading: boolean) => set({ isLoading }),
  setError: (error: string | null) => set({ error }),
  resetGeneration: () =>
    set({
      input: initialInput,
      currentJob: null,
      currentVideo: null,
      isLoading: false,
      error: null
    })
}));
