// Generated by GitHub Copilot
import Constants from "expo-constants";

export type AspectRatio = "9:16" | "1:1" | "16:9";
export type JobStatus = "queued" | "processing" | "completed" | "failed";

export interface UploadImageResponse {
  image_id: string;
  filename: string;
  content_type: string;
  image_url: string;
  created_at: string;
}

export interface GenerateVideoRequest {
  image_id: string;
  prompt: string;
  duration_seconds: number;
  aspect_ratio: AspectRatio;
}

export interface JobResponse {
  id: string;
  status: JobStatus;
  prompt: string;
  duration_seconds: number;
  aspect_ratio: AspectRatio;
  image_id: string;
  created_at: string;
  updated_at: string;
  video_id: string | null;
  error: string | null;
}

export interface GenerateVideoResponse {
  job: JobResponse;
}

export interface VideoResponse {
  id: string;
  source_image_id: string;
  prompt: string;
  duration_seconds: number;
  aspect_ratio: AspectRatio;
  video_url: string;
  created_at: string;
}

const extra = (Constants.expoConfig?.extra ?? {}) as { apiBaseUrl?: string };
const API_BASE_URL = extra.apiBaseUrl ?? "http://127.0.0.1:8000";

/**
 * Upload image from local URI using multipart/form-data.
 */
export async function uploadImage(imageUri: string): Promise<UploadImageResponse> {
  const formData = new FormData();
  formData.append("file", {
    uri: imageUri,
    name: "input.jpg",
    type: "image/jpeg"
  } as unknown as Blob);

  const response = await fetch(`${API_BASE_URL}/upload-image`, {
    method: "POST",
    body: formData
  });

  if (!response.ok) {
    throw new Error(await safeErrorMessage(response));
  }

  return (await response.json()) as UploadImageResponse;
}

/**
 * Create a generation job on the backend.
 */
export async function generateVideo(payload: GenerateVideoRequest): Promise<GenerateVideoResponse> {
  const response = await fetch(`${API_BASE_URL}/generate-video`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify(payload)
  });

  if (!response.ok) {
    throw new Error(await safeErrorMessage(response));
  }

  return (await response.json()) as GenerateVideoResponse;
}

/**
 * Fetch generation job status by job id.
 */
export async function getJob(jobId: string): Promise<JobResponse> {
  const response = await fetch(`${API_BASE_URL}/jobs/${jobId}`);

  if (!response.ok) {
    throw new Error(await safeErrorMessage(response));
  }

  return (await response.json()) as JobResponse;
}

/**
 * Fetch all generated videos.
 */
export async function listVideos(): Promise<VideoResponse[]> {
  const response = await fetch(`${API_BASE_URL}/videos`);

  if (!response.ok) {
    throw new Error(await safeErrorMessage(response));
  }

  return (await response.json()) as VideoResponse[];
}

/**
 * Fetch one generated video by id.
 */
export async function getVideo(videoId: string): Promise<VideoResponse> {
  const response = await fetch(`${API_BASE_URL}/videos/${videoId}`);

  if (!response.ok) {
    throw new Error(await safeErrorMessage(response));
  }

  return (await response.json()) as VideoResponse;
}

/**
 * Safely parse backend error message for user-friendly surfaced failures.
 */
async function safeErrorMessage(response: Response): Promise<string> {
  try {
    const data = (await response.json()) as { detail?: string };
    return data.detail ?? `Request failed with status ${response.status}`;
  } catch {
    return `Request failed with status ${response.status}`;
  }
}
