# Generated by GitHub Copilot
"""Application entrypoint for the Photo Motion AI backend."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from core.config import get_settings
from routes.generate import router as generate_router
from routes.jobs import router as jobs_router
from routes.upload import router as upload_router
from routes.videos import router as videos_router

settings = get_settings()

app = FastAPI(
    title="Photo Motion AI API",
    description="Backend API for image-to-video generation jobs.",
    version="0.1.0",
)


@app.get("/", tags=["health"])
async def root() -> dict[str, str]:
    """Return service metadata for root-level platform health checks."""
    return {"message": "Photo Motion AI API", "version": "0.1.0"}

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
async def health_check() -> dict[str, str]:
    """Return API health status for uptime and readiness checks."""
    return {"status": "ok", "service": "photo-motion-ai-backend"}


app.include_router(upload_router)
app.include_router(generate_router)
app.include_router(jobs_router)
app.include_router(videos_router)
