# Generated by GitHub Copilot
"""Internal model for job persistence evolution."""

from dataclasses import dataclass
from datetime import datetime

from schemas.job import JobStatus


@dataclass(slots=True)
class JobModel:
    """Dataclass model for future database mapping."""

    id: str
    status: JobStatus
    prompt: str
    duration_seconds: int
    aspect_ratio: str
    image_id: str
    created_at: datetime
    updated_at: datetime
    video_id: str | None = None
    error: str | None = None
