# Generated by GitHub Copilot
"""Internal model for generated video assets."""

from dataclasses import dataclass
from datetime import datetime


@dataclass(slots=True)
class VideoAssetModel:
    """Dataclass model for future DB/ORM mapping of generated videos."""

    id: str
    source_image_id: str
    prompt: str
    duration_seconds: int
    aspect_ratio: str
    video_url: str
    created_at: datetime
