# Generated by GitHub Copilot
"""Request and response schemas for upload and generation flows."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from schemas.job import JobResponse


class UploadImageResponse(BaseModel):
    """Metadata returned after successful image upload."""

    image_id: str
    filename: str
    content_type: str
    image_url: str
    created_at: datetime


class GenerateVideoRequest(BaseModel):
    """Input payload for creating an image-to-video generation job."""

    image_id: str = Field(..., description="Uploaded image identifier")
    prompt: str = Field(..., min_length=5, max_length=500)
    duration_seconds: int = Field(default=4, ge=2, le=12)
    aspect_ratio: Literal["9:16", "1:1", "16:9"] = "9:16"


class GenerateVideoResponse(BaseModel):
    """Response payload containing created job details."""

    job: JobResponse
