# Generated by GitHub Copilot
"""Schema models related to generation jobs."""

from datetime import datetime
from enum import Enum
from typing import Literal

from pydantic import BaseModel


class JobStatus(str, Enum):
    """Known states for a generation job lifecycle."""

    QUEUED = "queued"
    PROCESSING = "processing"
    COMPLETED = "completed"
    FAILED = "failed"


class JobResponse(BaseModel):
    """Public representation of a generation job."""

    id: str
    status: JobStatus
    prompt: str
    duration_seconds: int
    aspect_ratio: Literal["9:16", "1:1", "16:9"]
    image_id: str
    created_at: datetime
    updated_at: datetime
    video_id: str | None = None
    error: str | None = None
