# Generated by GitHub Copilot
"""Schema models related to generated videos."""

from datetime import datetime
from typing import Literal

from pydantic import BaseModel


class VideoResponse(BaseModel):
    """Public representation of a generated video asset."""

    id: str
    source_image_id: str
    prompt: str
    duration_seconds: int
    aspect_ratio: Literal["9:16", "1:1", "16:9"]
    video_url: str
    created_at: datetime
