# Generated by GitHub Copilot
"""In-memory and local file storage for uploads, jobs, and videos."""

from datetime import datetime, timezone
from pathlib import Path
from threading import Lock
from uuid import uuid4

from core.config import get_settings
from schemas.generate import UploadImageResponse
from schemas.job import JobResponse
from schemas.video import VideoResponse


class Storage:
    """Simple storage abstraction for local development and testing."""

    def __init__(self) -> None:
        """Initialize local directories and in-memory dictionaries."""
        settings = get_settings()
        self._lock = Lock()
        self._jobs: dict[str, JobResponse] = {}
        self._videos: dict[str, VideoResponse] = {}
        self._uploads: dict[str, UploadImageResponse] = {}

        base_dir = Path(settings.storage_dir)
        self._uploads_dir = base_dir / "uploads"
        self._uploads_dir.mkdir(parents=True, exist_ok=True)

    def save_upload(self, filename: str, content_type: str, content: bytes) -> UploadImageResponse:
        """Persist uploaded image bytes and return metadata for API responses."""
        image_id = f"img_{uuid4().hex[:12]}"
        extension = Path(filename).suffix or ".jpg"
        safe_name = f"{image_id}{extension}"
        file_path = self._uploads_dir / safe_name
        file_path.write_bytes(content)

        upload = UploadImageResponse(
            image_id=image_id,
            filename=filename,
            content_type=content_type,
            image_url=str(file_path.resolve()),
            created_at=datetime.now(timezone.utc),
        )
        with self._lock:
            self._uploads[image_id] = upload
        return upload

    def get_upload(self, image_id: str) -> UploadImageResponse | None:
        """Return uploaded image metadata for a given image id."""
        with self._lock:
            return self._uploads.get(image_id)

    def upsert_job(self, job: JobResponse) -> None:
        """Create or update a job record."""
        with self._lock:
            self._jobs[job.id] = job

    def get_job(self, job_id: str) -> JobResponse | None:
        """Fetch one job by id."""
        with self._lock:
            return self._jobs.get(job_id)

    def upsert_video(self, video: VideoResponse) -> None:
        """Create or update a video record."""
        with self._lock:
            self._videos[video.id] = video

    def get_video(self, video_id: str) -> VideoResponse | None:
        """Fetch one video by id."""
        with self._lock:
            return self._videos.get(video_id)

    def list_videos(self) -> list[VideoResponse]:
        """Return all stored videos."""
        with self._lock:
            return list(self._videos.values())


_storage_singleton = Storage()


def get_storage() -> Storage:
    """Return storage singleton for app-wide consistency."""
    return _storage_singleton
