// Generated by GitHub Copilot
import React from "react";
import { NavigationContainer, DefaultTheme } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { StatusBar } from "expo-status-bar";

import CreateVideoScreen from "./screens/CreateVideoScreen";
import HomeScreen from "./screens/HomeScreen";
import MyVideosScreen from "./screens/MyVideosScreen";
import PreviewScreen from "./screens/PreviewScreen";
import ProgressScreen from "./screens/ProgressScreen";
import SettingsScreen from "./screens/SettingsScreen";

export type RootStackParamList = {
  Home: undefined;
  CreateVideo: undefined;
  Progress: undefined;
  Preview: undefined;
  MyVideos: undefined;
  Settings: undefined;
};

const Stack = createNativeStackNavigator<RootStackParamList>();

const appTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    background: "#FAF8F2"
  }
};

/**
 * Root app component configuring mobile navigation stack.
 */
export default function App(): React.JSX.Element {
  return (
    <NavigationContainer theme={appTheme}>
      <StatusBar style="dark" />
      <Stack.Navigator
        initialRouteName="Home"
        screenOptions={{
          headerStyle: { backgroundColor: "#FAF8F2" },
          headerShadowVisible: false,
          headerTintColor: "#1E1B16",
          headerTitleStyle: { fontWeight: "700" }
        }}
      >
        <Stack.Screen name="Home" component={HomeScreen} options={{ title: "Photo Motion AI" }} />
        <Stack.Screen name="CreateVideo" component={CreateVideoScreen} options={{ title: "Create" }} />
        <Stack.Screen name="Progress" component={ProgressScreen} options={{ title: "Generating" }} />
        <Stack.Screen name="Preview" component={PreviewScreen} options={{ title: "Preview" }} />
        <Stack.Screen name="MyVideos" component={MyVideosScreen} options={{ title: "My Videos" }} />
        <Stack.Screen name="Settings" component={SettingsScreen} options={{ title: "Settings" }} />
      </Stack.Navigator>
    </NavigationContainer>
  );
}
