# Generated by GitHub Copilot
"""Worker module placeholder for future queue integrations."""

from schemas.generate import GenerateVideoRequest
from services.video_service import get_video_service


async def enqueue_generation(payload: GenerateVideoRequest) -> str:
    """Proxy job creation until a dedicated queue/worker is introduced."""
    service = get_video_service()
    job = await service.create_generation_job(payload)
    return job.id
