# Generated by GitHub Copilot
"""Video generation endpoints."""

from fastapi import APIRouter, HTTPException, status

from schemas.generate import GenerateVideoRequest, GenerateVideoResponse
from services.video_service import get_video_service

router = APIRouter(tags=["generate"])


@router.post("/generate-video", response_model=GenerateVideoResponse, status_code=status.HTTP_202_ACCEPTED)
async def generate_video(payload: GenerateVideoRequest) -> GenerateVideoResponse:
    """Create an asynchronous image-to-video generation job."""
    service = get_video_service()

    try:
        job = await service.create_generation_job(payload)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)) from exc

    return GenerateVideoResponse(job=job)
