# Generated by GitHub Copilot
"""Job status endpoints."""

from fastapi import APIRouter, HTTPException, status

from schemas.job import JobResponse
from services.video_service import get_video_service

router = APIRouter(tags=["jobs"])


@router.get("/jobs/{job_id}", response_model=JobResponse)
async def get_job(job_id: str) -> JobResponse:
    """Return status and output metadata for a generation job."""
    service = get_video_service()
    job = service.get_job(job_id)
    if job is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Job not found")

    return job
