# Generated by GitHub Copilot
"""Image upload endpoint."""

from fastapi import APIRouter, File, HTTPException, UploadFile, status

from core.storage import get_storage
from schemas.generate import UploadImageResponse
from services.image_validator import validate_image_upload

router = APIRouter(tags=["upload"])


@router.post("/upload-image", response_model=UploadImageResponse, status_code=status.HTTP_201_CREATED)
async def upload_image(file: UploadFile = File(...)) -> UploadImageResponse:
    """Store an uploaded image and return its metadata."""
    validate_image_upload(file)

    content = await file.read()
    if not content:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Uploaded file is empty")

    storage = get_storage()
    return storage.save_upload(filename=file.filename or "upload.jpg", content_type=file.content_type or "image/jpeg", content=content)
