# Generated by GitHub Copilot
"""Video retrieval endpoints."""

from fastapi import APIRouter, HTTPException, status

from schemas.video import VideoResponse
from services.video_service import get_video_service

router = APIRouter(tags=["videos"])


@router.get("/videos", response_model=list[VideoResponse])
async def list_videos() -> list[VideoResponse]:
    """Return all generated videos for the current environment."""
    service = get_video_service()
    return service.list_videos()


@router.get("/videos/{video_id}", response_model=VideoResponse)
async def get_video(video_id: str) -> VideoResponse:
    """Return a generated video by its id."""
    service = get_video_service()
    video = service.get_video(video_id)
    if video is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Video not found")

    return video
