# Generated by GitHub Copilot
"""Input validation utilities for uploaded images."""

from fastapi import HTTPException, UploadFile, status

ALLOWED_CONTENT_TYPES = {"image/jpeg", "image/png", "image/webp"}
MAX_FILE_SIZE_BYTES = 10 * 1024 * 1024


def validate_image_upload(file: UploadFile) -> None:
    """Validate basic upload constraints to reduce abuse and malformed input risk."""
    if file.content_type not in ALLOWED_CONTENT_TYPES:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Unsupported file type. Use JPEG, PNG, or WEBP.",
        )

    # Security note: this is a quick size check from multipart metadata when available.
    # A full production implementation should enforce reverse-proxy/body size limits too.
    size_header = file.headers.get("content-length") if file.headers else None
    if size_header and size_header.isdigit() and int(size_header) > MAX_FILE_SIZE_BYTES:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="File is too large. Max size is 10MB.",
        )
