# Generated by GitHub Copilot
"""Helpers to transform user prompts into provider-friendly prompts."""


def build_provider_prompt(user_prompt: str, duration_seconds: int, aspect_ratio: str) -> str:
    """Create a stable prompt string to improve provider output consistency."""
    return (
        f"{user_prompt.strip()}. "
        f"Create smooth camera-aware motion, cinematic quality, "
        f"duration {duration_seconds}s, aspect ratio {aspect_ratio}, "
        "no flicker, no jitter, preserve subject identity."
    )
