# Generated by GitHub Copilot
"""Provider abstraction for pluggable AI video generation services."""

from abc import ABC, abstractmethod

from schemas.generate import GenerateVideoRequest


class VideoProviderBase(ABC):
    """Base contract for image-to-video AI providers."""

    @abstractmethod
    async def generate_video(self, payload: GenerateVideoRequest) -> str:
        """Generate a video and return a playable URL."""
