# Generated by GitHub Copilot
"""Mock provider that simulates async image-to-video generation."""

import asyncio

from core.config import get_settings
from schemas.generate import GenerateVideoRequest
from services.provider_base import VideoProviderBase


class MockVideoProvider(VideoProviderBase):
    """Mock implementation used during local development and testing."""

    async def generate_video(self, payload: GenerateVideoRequest) -> str:
        """Simulate provider processing delay and return a sample video URL."""
        settings = get_settings()
        await asyncio.sleep(settings.mock_provider_delay_seconds)

        # TODO: Replace with real provider integration (Runway/fal/Replicate).
        if payload.aspect_ratio == "9:16":
            return "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"
        if payload.aspect_ratio == "1:1":
            return "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"
        return "https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"
