# Generated by GitHub Copilot
"""Business logic for image-to-video generation jobs."""

import asyncio
from datetime import datetime, timezone
from uuid import uuid4

from core.storage import get_storage
from schemas.generate import GenerateVideoRequest
from schemas.job import JobResponse, JobStatus
from schemas.video import VideoResponse
from services.prompt_builder import build_provider_prompt
from services.provider_base import VideoProviderBase
from services.provider_mock import MockVideoProvider


class VideoService:
    """Service layer that orchestrates job lifecycle and provider calls."""

    def __init__(self, provider: VideoProviderBase) -> None:
        """Initialize the service with a provider implementation."""
        self._provider = provider
        self._storage = get_storage()

    async def create_generation_job(self, payload: GenerateVideoRequest) -> JobResponse:
        """Validate input, create a queued job, and schedule async processing."""
        upload = self._storage.get_upload(payload.image_id)
        if upload is None:
            raise ValueError("Invalid image_id. Upload an image first.")

        now = datetime.now(timezone.utc)
        job_id = f"job_{uuid4().hex[:12]}"

        job = JobResponse(
            id=job_id,
            status=JobStatus.QUEUED,
            prompt=payload.prompt,
            duration_seconds=payload.duration_seconds,
            aspect_ratio=payload.aspect_ratio,
            image_id=payload.image_id,
            created_at=now,
            updated_at=now,
            video_id=None,
            error=None,
        )
        self._storage.upsert_job(job)
        asyncio.create_task(self._process_job(job_id=job_id, payload=payload))
        return job

    async def _process_job(self, job_id: str, payload: GenerateVideoRequest) -> None:
        """Execute provider generation and persist either success or failure results."""
        existing = self._storage.get_job(job_id)
        if existing is None:
            return

        processing_job = existing.model_copy(update={"status": JobStatus.PROCESSING, "updated_at": datetime.now(timezone.utc)})
        self._storage.upsert_job(processing_job)

        try:
            enhanced_prompt = build_provider_prompt(payload.prompt, payload.duration_seconds, payload.aspect_ratio)
            provider_payload = payload.model_copy(update={"prompt": enhanced_prompt})
            video_url = await self._provider.generate_video(provider_payload)

            video = VideoResponse(
                id=f"vid_{uuid4().hex[:12]}",
                source_image_id=payload.image_id,
                prompt=payload.prompt,
                duration_seconds=payload.duration_seconds,
                aspect_ratio=payload.aspect_ratio,
                video_url=video_url,
                created_at=datetime.now(timezone.utc),
            )
            self._storage.upsert_video(video)

            completed_job = processing_job.model_copy(
                update={
                    "status": JobStatus.COMPLETED,
                    "video_id": video.id,
                    "updated_at": datetime.now(timezone.utc),
                    "error": None,
                }
            )
            self._storage.upsert_job(completed_job)
        except Exception as exc:  # noqa: BLE001
            failed_job = processing_job.model_copy(
                update={
                    "status": JobStatus.FAILED,
                    "updated_at": datetime.now(timezone.utc),
                    "error": str(exc),
                }
            )
            self._storage.upsert_job(failed_job)

    def get_job(self, job_id: str) -> JobResponse | None:
        """Fetch a single job by id."""
        return self._storage.get_job(job_id)

    def list_videos(self) -> list[VideoResponse]:
        """Return videos sorted by newest first."""
        return sorted(self._storage.list_videos(), key=lambda item: item.created_at, reverse=True)

    def get_video(self, video_id: str) -> VideoResponse | None:
        """Fetch a single video by id."""
        return self._storage.get_video(video_id)


_video_service_singleton = VideoService(provider=MockVideoProvider())


def get_video_service() -> VideoService:
    """Return service singleton for API routes."""
    return _video_service_singleton
