# Generated by GitHub Copilot
"""Pytest fixtures for backend API tests."""

import os
import time
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# Generated by GitHub Copilot
# Set env before importing app-level modules that cache settings/singletons.
os.environ.setdefault("APP_ENV", "test")
os.environ.setdefault("MOCK_PROVIDER_DELAY_SECONDS", "1")
os.environ.setdefault("STORAGE_DIR", "/tmp/photo-motion-ai-test-data")
os.environ.setdefault("CORS_ORIGINS", "http://localhost:8081")

from core.storage import get_storage
from main import app


@pytest.fixture(autouse=True)
def reset_state() -> None:
    """Reset in-memory storage between tests to avoid cross-test leakage."""
    storage = get_storage()
    storage._jobs.clear()  # noqa: SLF001
    storage._videos.clear()  # noqa: SLF001
    storage._uploads.clear()  # noqa: SLF001


@pytest.fixture(scope="session", autouse=True)
def prepare_storage_dir() -> None:
    """Ensure temporary storage path exists for file upload tests."""
    path = Path("/tmp/photo-motion-ai-test-data/uploads")
    path.mkdir(parents=True, exist_ok=True)


@pytest.fixture
def client() -> TestClient:
    """Return a FastAPI test client."""
    return TestClient(app)


def wait_for_condition(predicate, timeout_seconds: float = 5.0, poll_every: float = 0.2) -> bool:
    """Poll until predicate is true or timeout expires."""
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(poll_every)
    return False
