# Generated by GitHub Copilot
"""Health endpoint tests."""

from fastapi.testclient import TestClient


# Generated by GitHub Copilot
def test_health_endpoint(client: TestClient) -> None:
    """Health endpoint should return service readiness."""
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"


# Generated by GitHub Copilot
def test_root_endpoint(client: TestClient) -> None:
    """Root endpoint should return basic API metadata."""
    response = client.get("/")
    assert response.status_code == 200
    body = response.json()
    assert body["message"] == "Photo Motion AI API"
    assert body["version"] == "0.1.0"
