# Generated by GitHub Copilot
"""End-to-end API tests for upload and generation flow."""

import time

from fastapi.testclient import TestClient


def wait_for_condition(predicate, timeout_seconds: float = 5.0, poll_every: float = 0.2) -> bool:
    """Poll until predicate is true or timeout expires."""
    deadline = time.time() + timeout_seconds
    while time.time() < deadline:
        if predicate():
            return True
        time.sleep(poll_every)
    return False


# Generated by GitHub Copilot
def test_upload_and_generate_flow(client: TestClient) -> None:
    """Should upload image, create job, complete generation, and return video."""
    upload_response = client.post(
        "/upload-image",
        files={"file": ("sample.png", b"fake-image-bytes", "image/png")},
    )
    assert upload_response.status_code == 201
    image_id = upload_response.json()["image_id"]

    generate_response = client.post(
        "/generate-video",
        json={
            "image_id": image_id,
            "prompt": "Add cinematic forward camera motion with subtle parallax",
            "duration_seconds": 4,
            "aspect_ratio": "9:16",
        },
    )
    assert generate_response.status_code == 202
    job = generate_response.json()["job"]
    assert job["status"] == "queued"

    job_id = job["id"]

    latest_job: dict[str, object] = {}

    def _job_completed() -> bool:
        nonlocal latest_job
        result = client.get(f"/jobs/{job_id}")
        if result.status_code != 200:
            return False
        latest_job = result.json()
        return latest_job.get("status") in {"completed", "failed"}

    assert wait_for_condition(_job_completed, timeout_seconds=8.0)
    assert latest_job["status"] == "completed"
    assert latest_job["video_id"] is not None

    video_id = latest_job["video_id"]
    single_video = client.get(f"/videos/{video_id}")
    assert single_video.status_code == 200

    video_list = client.get("/videos")
    assert video_list.status_code == 200
    assert len(video_list.json()) >= 1


# Generated by GitHub Copilot
def test_generate_with_invalid_image_id(client: TestClient) -> None:
    """Should reject generation request when image id is unknown."""
    response = client.post(
        "/generate-video",
        json={
            "image_id": "img_does_not_exist",
            "prompt": "Simple pan motion",
            "duration_seconds": 4,
            "aspect_ratio": "1:1",
        },
    )

    assert response.status_code == 400
    assert "Invalid image_id" in response.json()["detail"]
